version: '3'
services:
  tweet-ui:
    ports:
      - '9000:9000'
    image: 'nikseredinskiy/tweet-ui:latest'
    container_name: 'tweet-api_tweet-ui_1'
    networks:
      - tweet-api-network
  tweet-api:
    ports:
      - '8080:8080'
    image: 'nikseredinskiy/tweet-api:latest'
    container_name: 'tweet-api_tweet-api_1'
    networks:
      - tweet-api-network
  sentiment-analysis:
    ports:
      - '8000:8000'
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    image: 'nikseredinskiy/sentiment-analysis:latest'
    container_name: 'tweet-api_sentiment-analysis_1'
    networks:
      - tweet-api-network
networks:
  tweet-api-network:
    driver: bridge      
